Add Lesson_3
Kosarev90/JavaCoreLevel_1 pull request #4
Opened 2021-10-11 10:08 UTC by Kosarev90

2021-10-11 12:48 UTC, Kosarev90 commented on src/Home_Work/Lesson_3.java
> +    public static void arrayMaxMin() {
```suggestion
    public static void arrayMaxMin() { int[] array = {3, 23, 33, 21, 1, 32, 54, 25, 5};
        Arrays.sort(array);
        System.out.println(Arrays.toString(array));
        System.out.println(array[0]);
        System.out.println(array[array.length - 1]);
```

2021-10-13 22:35 UTC, OKrylov requested changes
В целом все хорошо, но обратите внимание на замечания

2021-10-13 22:35 UTC, OKrylov commented on src/Home_Work/Lesson_3.java
> +        int MaxInt = Integer.length;
переменные именуются с прописной буквы

2021-10-13 22:35 UTC, OKrylov commented on src/Home_Work/Lesson_3.java
> +        int[] Integer = {0, 0, 1, 1, 0, 0, 1, 1, 0, 0};
плохая практика использовать типы в качестве именования, поскольку легко запутаться что есть что

2021-10-13 22:35 UTC, OKrylov commented on src/Home_Work/Lesson_3.java
> +        Arrays.sort(array);
если массив уже отсортирован, то мы можем просто взять первый и последний элементы

2021-10-13 22:35 UTC, OKrylov commented on src/Home_Work/Lesson_3.java
> +            }
поиск минимального выполняется на каждой итерации при поиске максимального, циклы лучше разделить

2021-10-15 08:57 UTC, merged